-- ==========================================================
-- FILE: MON_28056_FULL_SCRIPT.sql
-- PROJECT: Smart Retail Inventory System
-- AUTHOR: BYISHIMO Kevin (ID: 28056)
-- DESCRIPTION: DDL for tables and DML for bulk data generation
-- ==========================================================

-- 1. CLEANUP (Drop existing objects to start fresh)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE supplier_product CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE sales CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE suppliers CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE holiday_calendar CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE audit_log CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Ignore errors if tables don't exist
END;
/

-- 2. TABLE CREATION
CREATE TABLE Suppliers (
    Supplier_ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Supplier_Name   VARCHAR2(100) NOT NULL,
    Contact_Email   VARCHAR2(100) UNIQUE NOT NULL,
    Phone           VARCHAR2(20),
    Created_At      DATE DEFAULT SYSDATE
);

CREATE TABLE Products (
    Product_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_Name    VARCHAR2(100) NOT NULL,
    Price           NUMBER(10,2) NOT NULL CHECK (Price > 0),
    Quantity        NUMBER DEFAULT 0 CHECK (Quantity >= 0),
    Supplier_ID     NUMBER,
    Created_At      DATE DEFAULT SYSDATE,
    Last_Updated    DATE DEFAULT SYSDATE,
    CONSTRAINT fk_prod_supp FOREIGN KEY (Supplier_ID) REFERENCES Suppliers(Supplier_ID)
);

CREATE TABLE Sales (
    Sale_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_ID      NUMBER NOT NULL,
    Quantity_Sold   NUMBER NOT NULL CHECK (Quantity_Sold > 0),
    Sale_Date       DATE DEFAULT SYSDATE,
    CONSTRAINT fk_sale_prod FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID)
);

CREATE TABLE holiday_calendar (
    holiday_date DATE PRIMARY KEY,
    description  VARCHAR2(100)
);

CREATE TABLE audit_log (
    audit_id     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR2(30),
    action_date  DATE DEFAULT SYSDATE,
    table_name   VARCHAR2(50),
    operation    VARCHAR2(20),
    status       VARCHAR2(20),
    remarks      VARCHAR2(100)
);

-- 3. DATA GENERATION (400+ Rows)
BEGIN
    -- Suppliers
    FOR i IN 1..20 LOOP
        INSERT INTO Suppliers (Supplier_Name, Contact_Email, Phone)
        VALUES ('Supplier_'||i, 'contact'||i||'@supply.com', '078'||TRUNC(DBMS_RANDOM.VALUE(1000000,9999999)));
    END LOOP;

    -- Products
    FOR i IN 1..100 LOOP
        INSERT INTO Products (Product_Name, Price, Quantity, Supplier_ID)
        VALUES ('Product_'||i, ROUND(DBMS_RANDOM.VALUE(10,500),2), TRUNC(DBMS_RANDOM.VALUE(50,200)), TRUNC(DBMS_RANDOM.VALUE(1,20)));
    END LOOP;

    -- Sales
    FOR i IN 1..300 LOOP
        INSERT INTO Sales (Product_ID, Quantity_Sold, Sale_Date)
        VALUES (TRUNC(DBMS_RANDOM.VALUE(1,100)), TRUNC(DBMS_RANDOM.VALUE(1,5)), SYSDATE - TRUNC(DBMS_RANDOM.VALUE(1,60)));
    END LOOP;
    
    -- Holidays
    INSERT INTO holiday_calendar VALUES (TO_DATE('2025-06-01','YYYY-MM-DD'), 'National Day');
    INSERT INTO holiday_calendar VALUES (TO_DATE('2025-06-15','YYYY-MM-DD'), 'Founders Day');
    
    COMMIT;
END;
/